import { CentroCosto } from "@/types/centroCosto";
import { Cuenta } from "@/types/cuenta";
import { Gasto } from "@/types/gasto";
import { Proyecto } from "@/types/proyecto";

const roles = [
  {
    id: "A",
    nombre: "Administrador",
  },
  {
    id: "R",
    nombre: "Aprobador",
  },
  {
    id: "U",
    nombre: "Usuario",
  },
];
// const usuarios = [
//   {
//     id: "6",
//     nombre: "Willimas",
//     apellido: "Estrada",
//     rut: "20.000.987-2",
//     email: "willimas.estrada@kyros.cl",
//     telefono: "+56 956278786",
//     banco: "012",
//     tipoid_cuenta_contable: "Cta Cte",
//     nroid_cuenta_contable: "00-1029220-100928",
//     correoid_cuenta_contable: "willimas.estrada@kyros.cl",
//     password: "1234",
//     foto: "https://cdn.pixabay.com/photo/2020/07/21/16/10/pokemon-5426712_640.png",
//     sociedades: [
//       // Información sobre sociedades
//       { id: "1", nombre: "Kyros Ltda.", rol: "Administrador", activo: true },
//       { id: "2", nombre: "Kyros SPA.", rol: "", activo: false },
//       { id: "3", nombre: "2call SPA.", rol: "", activo: false },
//       { id: "4", nombre: "Inversiones SPA.", rol: "", activo: false },
//       { id: "5", nombre: "Inversiones C&R.", rol: "", activo: false },
//       { id: "6", nombre: "Inversiones ESPA.", rol: "", activo: false },
//     ],
//     activo: true,
//   },
//   {
//     id: "2",
//     nombre: "Matias",
//     apellido: "Erazo",
//     rut: "10.540.987-5",
//     email: "matias.erazo@kyros.cl",
//     telefono: "+56 956278786",
//     banco: "012",
//     tipoid_cuenta_contable: "Cta Cte",
//     nroid_cuenta_contable: "00-1029220-100928",
//     correoid_cuenta_contable: "matias.erazo@kyros.cl",
//     password: "1234",
//     foto: "https://cdn.pixabay.com/photo/2020/07/21/16/10/pokemon-5426712_640.png",
//     sociedades: [
//       // Información sobre sociedades
//       { id: "1", nombre: "Kyros Ltda.", rol: "Administrador", activo: true },
//       { id: "2", nombre: "Kyros SPA.", rol: "", activo: false },
//       { id: "3", nombre: "2call SPA.", rol: "", activo: false },
//       { id: "4", nombre: "Inversiones SPA.", rol: "", activo: false },
//       { id: "5", nombre: "Inversiones C&R.", rol: "", activo: false },
//       { id: "6", nombre: "Inversiones ESPA.", rol: "", activo: false },
//     ],
//     activo: true,
//   },
//   {
//     id: "4",
//     nombre: "Benjamin",
//     apellido: "Arce",
//     rut: "14.540.987-3",
//     email: "benjamin.arce@kyros.cl",
//     telefono: "+56 956278786",
//     banco: "012",
//     tipoid_cuenta_contable: "Cta Cte",
//     nroid_cuenta_contable: "00-1029220-100928",
//     correoid_cuenta_contable: "benjamin.arce@kyros.cl",
//     password: "1234",
//     foto: "https://cdn.pixabay.com/photo/2020/07/21/16/10/pokemon-5426712_640.png",
//     sociedades: [
//       // Información sobre sociedades
//       { id: "1", nombre: "Kyros Ltda.", rol: "Administrador", activo: true },
//       { id: "2", nombre: "Kyros SPA.", rol: "", activo: false },
//       { id: "3", nombre: "2call SPA.", rol: "", activo: false },
//       { id: "4", nombre: "Inversiones SPA.", rol: "", activo: false },
//       { id: "5", nombre: "Inversiones C&R.", rol: "", activo: false },
//       { id: "6", nombre: "Inversiones ESPA.", rol: "", activo: false },
//     ],
//     activo: true,
//   },
//   {
//     id: "3",
//     nombre: "Nelson",
//     apellido: "Soto",
//     rut: "13.670.785-K",
//     email: "nelson.soto@kyros.cl",
//     telefono: "+56 956278786",
//     banco: "012",
//     tipoid_cuenta_contable: "Cta Cte",
//     nroid_cuenta_contable: "00-1029220-100928",
//     correoid_cuenta_contable: "nelson.soto@kyros.cl",
//     password: "1234",
//     foto: "https://cdn.pixabay.com/photo/2020/07/21/16/10/pokemon-5426712_640.png",
//     sociedades: [
//       // Información sobre sociedades
//       { id: "1", nombre: "Kyros Ltda.", rol: "Administrador", activo: true },
//       { id: "2", nombre: "Kyros SPA.", rol: "", activo: false },
//       { id: "3", nombre: "2call SPA.", rol: "", activo: false },
//       { id: "4", nombre: "Inversiones SPA.", rol: "", activo: false },
//       { id: "5", nombre: "Inversiones C&R.", rol: "", activo: false },
//       { id: "6", nombre: "Inversiones ESPA.", rol: "", activo: false },
//     ],
//     activo: true,
//   },
//   {
//     id: "1",
//     nombre: "Pablo",
//     apellido: "Pacheco",
//     rut: "8.432.934-1",
//     email: "admin@b1expenses.com",
//     telefono: "+56 956278786",
//     banco: "012",
//     tipoid_cuenta_contable: "Cta Cte",
//     nroid_cuenta_contable: "00-1029220-100928",
//     correoid_cuenta_contable: "pablo.pacheco@kyros.cl",
//     password: "1234",
//     foto: "https://cdn.pixabay.com/photo/2020/07/21/16/10/pokemon-5426712_640.png",
//     sociedades: [
//       // Información sobre sociedades
//       { id: "1", nombre: "Kyros Ltda.", rol: "Administrador", activo: true },
//       { id: "2", nombre: "Kyros SPA.", rol: "", activo: false },
//       { id: "3", nombre: "2call SPA.", rol: "", activo: false },
//       { id: "4", nombre: "Inversiones SPA.", rol: "", activo: false },
//       { id: "5", nombre: "Inversiones C&R.", rol: "", activo: false },
//       { id: "6", nombre: "Inversiones ESPA.", rol: "Usuario", activo: true },
//     ],
//     activo: true,
//   },
//   {
//     id: "5",
//     nombre: "Roberto",
//     apellido: "Ortega",
//     rut: "12.432.934-1",
//     email: "roberto.ortega@kyros.cl",
//     telefono: "+56 956278786",
//     banco: "012",
//     tipoid_cuenta_contable: "Cta Cte",
//     nroid_cuenta_contable: "00-1029220-100928",
//     correoid_cuenta_contable: "roberto.ortega@kyros.cl",
//     password: "1234",
//     foto: "https://cdn.pixabay.com/photo/2020/07/21/16/10/pokemon-5426712_640.png",
//     sociedades: [
//       // Información sobre sociedades
//       { id: "1", nombre: "Kyros Ltda.", rol: "Administrador", activo: true },
//       { id: "2", nombre: "Kyros SPA.", rol: "", activo: false },
//       { id: "3", nombre: "2call SPA.", rol: "", activo: false },
//       { id: "4", nombre: "Inversiones SPA.", rol: "", activo: false },
//       { id: "5", nombre: "Inversiones C&R.", rol: "", activo: false },
//       { id: "6", nombre: "Inversiones ESPA.", rol: "", activo: false },
//     ],
//     activo: true,
//   },
// ];
// const sociedades = [
//   {
//     id: "1",
//     nombre: "Kyros Ltda.",
//     rut: "76.567.638-8",
//     encargado: "Jaime Valdez",
//     correo: "comercial@kyros.cl",
//     activo: true,
//   },
//   {
//     id: "2",
//     nombre: "Kyros SPA.",
//     rut: "76.567.738-8",
//     encargado: "Jorge Gonzales",
//     correo: "soportel@kyros.cl",
//     activo: true,
//   },
//   {
//     id: "3",
//     nombre: "2call SPA.",
//     rut: "74.567.738-8",
//     encargado: "Hector Silva",
//     correo: "soportel@2call.cl",
//     activo: true,
//   },
//   {
//     id: "4",
//     nombre: "Inversiones SPA.",
//     rut: "54.123.738-8",
//     encargado: "Paolo Rojas",
//     correo: "soportel@inversiones.cl",
//     activo: true,
//   },
//   {
//     id: "5",
//     nombre: "Inversiones C&R.",
//     rut: "14.123.738-8",
//     encargado: "Juan Rojas",
//     correo: "soportel@inversionescr.cl",
//     activo: true,
//   },
//   {
//     id: "6",
//     nombre: "Inversiones ESPA.",
//     rut: "74.123.778-8",
//     encargado: "Pedro Pedro",
//     correo: "soportel@inversionesespa.cl",
//     activo: true,
//   },
// ];

// const sociedadesSeleccion = [
//   {
//     id: "1",
//     nombre: "Kyros Ltda. como Administrador",
//     activo: true,
//   },
//   {
//     id: "2",
//     nombre: "Kyros SPA. como Administrador",
//     activo: true,
//   },
//   {
//     id: "3",
//     nombre: "2call SPA. como Aprobador",
//     activo: true,
//   },
//   {
//     id: "4",
//     nombre: "Inversiones SPA. como Administrador",
//     activo: true,
//   },
//   {
//     id: "5",
//     nombre: "Inversiones C&R. como Usuario",
//     activo: true,
//   },
//   {
//     id: "6",
//     nombre: "Inversiones ESPA. como Aprobador",
//     activo: true,
//   },
// ];

// const proyectos: Proyecto[] = [
//   {
//     id: "p1",
//     nombre: "Integración SAP - WMS",
//     descripcion: "Primer proyecto",
//     fecha_inicio: new Date("2024-01-01"),
//     fecha_fin: new Date("2024-12-31"),
//     activo: true,
//   },
//   {
//     id: "p2",
//     nombre: "Implementación SAP Books",
//     descripcion: "Segundo proyecto",
//     fecha_inicio: new Date("2024-01-01"),
//     fecha_fin: new Date("2024-12-31"),
//     activo: true,
//   },
//   {
//     id: "p3",
//     nombre: "HEEL Libro Legal",
//     descripcion: "Tercer proyecto",
//     fecha_inicio: new Date(),
//     fecha_fin: new Date("2024-12-31"),
//     activo: true,
//   },
// ];

// // const cc: CentroCosto[] = [
// //   {
// //     id: "cc1",
// //     nombre: "Administración",
// //     descripcion: "Primer centro",
// //     activo: true,
// //   },
// //   {
// //     id: "cc2",
// //     nombre: "Consultoría",
// //     descripcion: "Segundo centro",
// //     activo: true,
// //   },
// //   {
// //     id: "cc3",
// //     nombre: "Desarrollo",
// //     descripcion: "Tercer centro",
// //     activo: true,
// //   },
// //   {
// //     id: "cc4",
// //     nombre: "Finanzas",
// //     descripcion: "Cuarto centro",
// //     activo: true,
// //   },
// //   {
// //     id: "cc5",
// //     nombre: "Abastecimiento",
// //     descripcion: "Quinto centro",
// //     activo: true,
// //   },
// //   {
// //     id: "cc6",
// //     nombre: "CRM",
// //     descripcion: "Sexto centro",
// //     activo: true,
// //   },
// // ];

// const gastos: Gasto[] = [
//   {
//     id: "1",
//     nombre: "Gastos de Hospedaje",
//     id_cuenta_contable: "5-001-000",
//     descripcion: "Gasto de alojamiento",
//     activo: true,
//   },
//   {
//     id: "2",
//     nombre: "Gastos de Transporte",
//     id_cuenta_contable: "5-001-005",
//     descripcion: "Gastos de movilización",
//     activo: false,
//   },
//   {
//     id: "3",
//     nombre: "Gastos de Tecnologia",
//     id_cuenta_contable: "5-001-002",
//     descripcion: "Gastos para articulo tecnologicos",
//     activo: true,
//   },
//   {
//     id: "4",
//     nombre: "Gastos de Almuerzo",
//     id_cuenta_contable: "5-001-003",
//     descripcion: "Gastos de colación o alimentación",
//     activo: true,
//   },
// ];
// const cuentasContables: Cuenta[] = [
//   {
//     id: "5-001-001",

//     nombre: "Cuenta contable 1",
//     descripcion: "Descripción cuenta contable 1",
//     activo: true,
//   },
//   {
//     id: "5-001-002",

//     nombre: "Cuenta contable 2",
//     descripcion: "Descripción cuenta contable 2",
//     activo: true,
//   },

//   {
//     id: "5-001-003",

//     nombre: "Cuenta contable 3",
//     descripcion: "Descripción cuenta contable 3",
//     activo: true,
//   },
//   {
//     id: "5-001-004",

//     nombre: "Cuenta contable 4",
//     descripcion: "Descripción cuenta contable 4",
//     activo: true,
//   },
//   {
//     id: "5-001-005",

//     nombre: "Cuenta contable 5",
//     descripcion: "Descripción cuenta contable 5",
//     activo: true,
//   },
// ];

// const fondos: FondoList[] = [
//   {
//     numero: 557,
//     estado: "REVISION",
//     fecha_creacion: "02-06-2024",
//     fechaRequerida: "13-06-2024",
//     concepto: "Realizar gastos",
//     proyecto: "Proyecto 2",
//     creador: "Jorge Pérez",
//     monto: 10000,
//   },
//   {
//     numero: 558,
//     estado: "APROBADO",
//     fechaCreacion: "15-05-2024",
//     fechaRequerida: "01-06-2024",
//     concepto: "Gastos de alimentación",
//     proyecto: "Proyecto 3",
//     creador: "Alberto A. Maluenda",
//     monto: 250000,
//   },
//   {
//     numero: 559,
//     estado: "RECHAZADO",
//     fechaCreacion: "15-05-2024",
//     fechaRequerida: "01-06-2024",
//     concepto: "Gastos de alojamiento",
//     proyecto: "Proyecto 3",
//     creador: "Nelson Soto",
//     monto: 250000,
//   },
//   {
//     numero: 560,
//     estado: "BORRADOR",
//     fechaCreacion: "15-05-2024",
//     fechaRequerida: "01-06-2024",
//     concepto: "Realizar gastos de viaje",
//     proyecto: "Proyecto 3",
//     creador: "Willimas Pepito",
//     monto: 250000,
//   },
//   {
//     numero: 561,
//     estado: "APROBADO",
//     fechaCreacion: "15-05-2024",
//     fechaRequerida: "01-06-2024",
//     concepto: "Realizar gastos de viaje",
//     proyecto: "Proyecto 3",
//     creador: "Willimas Pérez",
//     monto: 250000,
//   },
//   {
//     numero: 562,
//     estado: "APROBADO",
//     fechaCreacion: "15-05-2024",
//     fechaRequerida: "01-06-2024",
//     concepto: "Realizar gastos de viaje",
//     proyecto: "Proyecto 3",
//     creador: "Willimas Pérez",
//     monto: 250000,
//   },
//   {
//     numero: 563,
//     estado: "APROBADO",
//     fechaCreacion: "15-05-2024",
//     fechaRequerida: "01-06-2024",
//     concepto: "Quiero comprar implementos",
//     proyecto: "Proyecto 3",
//     creador: "Pablo D. Pepito",
//     monto: 250000,
//   },
//   {
//     numero: 564,
//     estado: "APROBADO",
//     fechaCreacion: "15-05-2024",
//     fechaRequerida: "01-06-2024",
//     concepto: "Insumos eléctricos",
//     proyecto: "Proyecto 3",
//     creador: "Pepito Álvarez",
//     monto: 250000,
//   },
//   {
//     numero: 565,
//     estado: "APROBADO",
//     fechaCreacion: "15-05-2024",
//     fechaRequerida: "01-06-2024",
//     concepto: "Reemplazo de escritorio (sillas, etc..)",
//     proyecto: "Proyecto 2",
//     creador: "Pepito Álvarez",
//     monto: 250000,
//   },
//   {
//     numero: 566,
//     estado: "REVISION",
//     fechaCreacion: "20-06-2024",
//     fechaRequerida: "25-07-2024",
//     concepto: "Realizar gastos 5",
//     proyecto: "Conjunto de viajes",
//     creador: "Alfonso Álvarez",
//     monto: 50000,
//   },
//   {
//     numero: 567,
//     estado: "REVISION",
//     fechaCreacion: "12-07-2024",
//     fechaRequerida: "13-08-2024",
//     concepto: "Necesito pagar comida",
//     proyecto: "Alpes",
//     creador: "Marcelo Mara",
//     monto: 9000,
//   },
// ];

// const bancos = [
//   { nombre: "BANCO DE CHILE", codigoSBIF: "001", activo: true },
//   {
//     nombre: "BANCO DEL ESTADO DE CHILE - BANCOESTADO",
//     codigoSBIF: "012",
//     activo: true,
//   },
//   { nombre: "BANCO INTERNACIONAL", codigoSBIF: "009", activo: true },
//   {
//     nombre: "BANCO DE CREDITO E INVERSIONES - BCI",
//     codigoSBIF: "016",
//     activo: true,
//   },
//   { nombre: "BANCO BICE", codigoSBIF: "028", activo: true },
//   { nombre: "BANCO FALABELLA", codigoSBIF: "051", activo: true },
//   { nombre: "BANCO ITAÚ CHILE", codigoSBIF: "039", activo: true },
//   { nombre: "BANCO PENTA", codigoSBIF: "056", activo: true },
//   { nombre: "BANCO PARIS", codigoSBIF: "057", activo: true },
//   { nombre: "BANCO RIPLEY", codigoSBIF: "053", activo: true },
//   { nombre: "BANCO SECURITY", codigoSBIF: "049", activo: true },
//   { nombre: "BANCO SANTANDER-CHILE", codigoSBIF: "037", activo: true },
//   { nombre: "BANCO BTG PACTUAL CHILE", codigoSBIF: "059", activo: true },
//   { nombre: "CORPBANCA", codigoSBIF: "027", activo: true },
//   { nombre: "DEUTSCHE BANK (CHILE)", codigoSBIF: "052", activo: true },
//   { nombre: "HSBC BANK (CHILE)", codigoSBIF: "031", activo: true },
//   { nombre: "RABOBANK CHILE (ex HNS BANCO)", codigoSBIF: "054", activo: true },
//   {
//     nombre: "BANCO CONSORCIO (ex BANCO MONEX)",
//     codigoSBIF: "055",
//     activo: true,
//   },
//   {
//     nombre: "BANCO BILBAO VIZCAYA ARGENTARIA, CHILE (BBVA)",
//     codigoSBIF: "504",
//     activo: true,
//   },
// ];

export {
  //roles,
  //fondos,
  //proyectos,
  //gastos,
  //cuentasContables,
  //sociedadesSeleccion,
  //sociedades,
  //usuarios,
  //bancos,
  roles,
};
